### ISSUE TITLE
no headers showing up

### ISSUE THREAD

**Issue by gagandaroach** [markbattistella/docsify-auto-headers#7]
I don't think this is working. I am looking to add section numbered heading to my dcosify project, and when I import this plugin I do not see any change.

The examples as well do not show any change.

~
Gagan

**Comment by markbattistella** [comment]
@gagandaroach thanks for pointing that out. I'll have to look into it when i get some spare time and see if i can add some other functions too. a reload seems to fix it but not ideal

**Comment by gagandaroach** [comment]
hi @markbattistella, let me know if there is a way I can help :)

**Comment by markbattistella** [comment]
@gagandaroach I think I solved the problem on the way it renders the numbers but I'm trying to solve this other bug at the moment thats popped up since changing the structure. once I have that working i will release it. the testing copy is in https://github.com/markbattistella/docsify-autoHeaders-docs/tree/mb/sidebar if you want to have a look? happy for you to spin it up and submit a pull request if you want :)

**Comment by gagandaroach** [comment]
I gave it a shot but I made some errors in importing the min.js version from the testing copy. 

My skillset is with CDN :), when main updates I can test from there.

**Comment by gagandaroach** [comment]
@markbattistella have you been able to vet and update the core plugin with this fix?

**Comment by markbattistella** [comment]
This should be fixed in v5.0.0
